# -------Gradle--------
org.gradle.jvmargs=-Xmx4g
org.gradle.daemon=true
org.gradle.parallel=true
# -------Plugins---------
jgitver=0.10.0-rc03
dependencyManagement=1.1.7
springframeworkBoot=3.4.1
johnrengelmanShadow=8.1.1
jib=3.4.4
sonarlint=4.2.4
spotless=6.25.0
lombok=8.10.2
# -------Versions--------
testcontainersBom=1.19.7

webjarsLocator=0.52
sockjs=1.5.1
stomp=2.3.4
bootstrap=5.2.3
jquery=3.7.1
springDocOpenapiUi=2.0.2

dockerJava=3.4.1
flywayCore=11.2.0
